describe('API GET', () => {
    beforeEach(() => {
        cy.visit('/');
    })
    it('elaboracao-prova-client/', () => {
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/elaboracao-prova-client/')
            .its('status')
            .should('equal', 200)
    })
    it('api/usuarios/sair', () => {
        cy.loginCadernoFalha('00000000000', '123456');
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/usuarios/sair')
            .its('status')
            .should('equal', 200)
    })
    it('/api/grupos/ObtemTodos', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/grupos/ObtemTodos')
            .its('status')
            .should('equal', 200)
    })
    it('/api/Funcoes/ObtemFuncoesUsuario', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Funcoes/ObtemFuncoesUsuario')
            .its('status')
            .should('equal', 200)
    })
    it('//ElaboracaoProvaAPI/api/grupos', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/grupos')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/ElmahErrors', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/ElmahErrors')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/eventos', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/eventos/')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/areas', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/areas')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/usuarios/paginados', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/usuarios/paginados')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Funcoes/ObtemPorModulo', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Funcoes/ObtemPorModulo')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/expurgo', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/expurgo/paginados')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/LogGeral', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/LogGeral')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/itemTipo', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/itemTipo')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/eventos', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/eventos/')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/itemStatus/Evento', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/itemStatus/Evento')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/papeisitemstatus', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/papeisitemstatus')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Armazenamento/ObterTiposConteudo', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Armazenamento/ObterTiposConteudo')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Alternativas', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Alternativas')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/AnoEscolar', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/AnoEscolar')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Blocos/paginados', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Blocos/paginados')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Cadernos/paginados', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Cadernos/paginados')
            .its('status')
            .should('equal', 200)
    })
    it('ElaboracaoProvaAPI/api/CadernoStatus', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/CadernoStatus')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Descritor/arvore', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Descritor/arvore')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Descritor/todos', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Descritor/todos')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Descritor/todos/folhas', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Descritor/todos/folhas')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Encomenda/totalPorUsuario', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Encomenda/totalPorUsuario')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Encomenda/itens/sumario', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Encomenda/itens/sumario')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/EncomendaUsuarios/ObtemPorEncomendaArea', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/EncomendaUsuarios/ObtemPorEncomendaArea')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Eventos/paginados', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Eventos/paginados')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Eventos/detalhados/paginados', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Eventos/detalhados/paginados')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Eventos/totalPorUsuario', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Eventos/totalPorUsuario')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Expurgo/paginados', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Expurgo/paginados')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Funcoes/tipo-funcao', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Funcoes/tipo-funcao')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Funcoes/ObtemPorModulo', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Funcoes/ObtemPorModulo')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Grupos/ObtemPorUsuario', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Grupos/ObtemPorUsuario')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/check', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/check')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/check/data-base', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/check/data-base')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/check/write-file', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/check/write-file')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/check/error-falha-acesso', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/check/error-falha-acesso')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Importacoes/templates/blocoPadrao', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Importacoes/templates/blocoPadrao')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Importacoes/templates/cadernoPadrao', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Importacoes/templates/cadernoPadrao')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Importacoes/templates/cadernoInep', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Importacoes/templates/cadernoInep')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/api/Importacoes/templates/rotacaoInep', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Importacoes/templates/rotacaoInep')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Importacoes/templates/blocoInep', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Importacoes/templates/blocoInep')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Importacoes/templates/itemPadrao', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Importacoes/templates/itemPadrao')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Importacoes/templates/itemInep', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Importacoes/templates/itemInep')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/ItemComentarios/paginado', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/ItemComentarios/paginado')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/ItemStatus/Encomenda', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/ItemStatus/Encomenda')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/ItemVersoes', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/ItemVersoes')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Itens/paginados', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Itens/paginados')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Itens/exportarItensCSV', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Itens/exportarItensCSV')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Itens/paginadosPorBloco', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Itens/paginadosPorBloco')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Itens/listaParaNavegacao', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Itens/listaParaNavegacao')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Itens/imagens/paginados', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Itens/imagens/paginados')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/LogGeral', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/LogGeral')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/LogGeral/paginados', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/LogGeral/paginados')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Papeis/grupoUsuario', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Papeis/grupoUsuario')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/TipoMedias', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/TipoMedias')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Usuarios/checkUsuarioExistente', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/Usuarios/checkUsuarioExistente')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/Usuarios/checkUsuarioExistente', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/CapaTag/capaTagValor/obtemPorTodos')
            .its('status')
            .should('equal', 200)
    })
    it('/ElaboracaoProvaAPI/api/DistribuicaoPedidos/paginados', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI/api/DistribuicaoPedidos/paginados')
            .its('status')
            .should('equal', 200)
    })
    it.only('/ElaboracaoProvaAPI//api/ItemDimensao/ObtemPorTipoVisualizacaoItem', () => {
        cy.loginCaderno('00000000000', '123456')
        cy.request('GET', 'http://homologa.elaboracaoprova.intranet.cesgranrio.org.br/ElaboracaoProvaAPI//api/ItemDimensao/ObtemPorTipoVisualizacaoItem')
            .its('status')
            .should('equal', 200)
    })
})









